# Generated by Django 4.1.1 on 2023-03-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
    ]
