# Generated by Django 4.1.1 on 2023-03-14 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_remove_register_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
